backend:
  name: github
  repo: ElijahBitkov/whiteblog
  branch: main
  

  
collections:
  - name: blog
    label: Blog
    folder: "src/posts/"
    media_folder: "."
    slug: "{{year}}-{{month}}-{{day}} {{hour}}:{{minute}}"
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
 
      